### ISSUE TITLE
Add / validate support for Linux / MacOSx

### ISSUE THREAD

**Issue by Stephanevg** [Stephanevg/PSHTML#54]
I would like to add / ensure the support of this module on:

- [X] Windows
- [x] Linux
- [ ] MacOsX

I have been testing this module on a windows machine (ps 5.1) 
I belive we have nothing that is super windows specific, but I would like to make sur of this, by adding at least one or two pester tests, that validated that the module still works, on other platforms then Windows.

**Comment by SeanEGray** [comment]
I thought I'd take a look at this one, because I think that it should be possible to get appveyor to handle the Linux tests for us (don't have a plan for MacOS, sorry).

I've run into a few issues around case sensitivity of files; we either need to rename files to match the case that they're referred to in the scripts, or change the scripts to match the current case of the files. Do you have a preference?

**Comment by Stijnc** [comment]
Is there anything else apart from the build system not supporting macOS? 
otherwise have a look at [Azure devops](https://azure.microsoft.com/en-us/services/devops/pipelines/ ). it supports the 3 os'es.

**Comment by Stephanevg** [comment]
Hey @Stijnc Thanks a lot for the tip! 👍 
Do you have existing repository (or knowledge of one) where we can go and look at, as an example?

**Comment by SeanEGray** [comment]
I notice you have a LinuxSupport feature branch now; would you prefer me to fork that one if I take a look at this again, or the dev branch?

**Comment by Stephanevg** [comment]
Hi Sean,

Yeah, it would make sense that you fork that one actually. I think I
corrected everything actually, but then Github started to make my life
difficult, with all their bugs this morning. The result was that the build
kept failing.
Perhaps you have more luck then me?

Also, you would totaly deserve to PR this one actually, because I looked in
your PR, to know which things needed to be fixed. So, perhaps this is just
an 'easy PR' for you now ;)
