### ISSUE TITLE
Receive object[] and not a string

### ISSUE THREAD

**Issue by Lasio74** [Stephanevg/PSHTML#55]
### Subject of the issue
receive in return an object[] and not a string causing extra work to format the output to a string
if we use it as a string, we receive only the first element of the array

can be easily fix for the V2.0.0 functions by updating Set-HTMLTag

### Steps to reproduce
`'The quick brown {0} jumps over the lazy dog' -f  (strong 'fox')`

### Expected behaviour
`The quick brown <strong>fox</strong> jumps over the lazy dog`

### Actual behaviour
`The quick brown <strong> jumps over the lazy dog`

**Comment by Stephanevg** [comment]
Hi @Lasio74 ,

Thanks for opening this issue 👍 

"Strong" is a difficult one, I agree. 
Since it is inline, in a complete sentence, it is really difficult to distringuish:
`
He is really a strong man
`

from 

`
He is really a *man*
`
(Where it would be <strong>man</strong>)

There for, you should seperate your 'strong' elements using a ';' as explained in the comment based help of the cmdlet:

```powershell
<#
    .SYNOPSIS
    Generates strong HTML tag.

    .Description
    This tag is a "Textual semantic" tag. To use it in a "P" tag, be sure to prefix it with a semicolon (";").
    See example for more details.

    .EXAMPLE
    p{
        "This is";strong {"cool"}
    }

    Will generate the following code

    <p>
        This is
        <strong>
        cool
        </strong>
    </p>

```

**Comment by Stephanevg** [comment]
Please re-open if you think this issue was closed incorrectly.
